DEFAULT_WINDOW_WIDTH = 2400
DEFAULT_WINDOW_HEIGHT = 1200

DEFAULT_GRAVITY = 9.81
DEFAULT_AIR_DENSITY = 1.225
DEFAULT_DRAG_COEFFICIENT = 0.47

DEFAULT_CANNON_HEIGHT = 0
DEFAULT_FIRING_ANGLE = 45
DEFAULT_CANNON_INITIAL_VELOCITY = 30

DEFAULT_CANNONBALL_MASS = 10
DEFAULT_CANNONBALL_RADIUS = 20