#Evironment Variables
DEFAULT_GRAVITATIONAL_ACCELERATION = 9.81
DEFAULT_AIR_DENSITY = 1

#Default Cannon Variables
DEFAULT_CANNON_HEIGHT = 0
DEFAULT_FIRING_ANGLE = 45
DEFAULT_CANNON_INITIAL_VELOCITY = 30

#Default Cannonball Variables
DEFAULT_CANNONBALL_MASS = 10
DEFAULT_CANNONBALL_RADIUS = 10
