#Graphic Variables
WINDOW_WIDTH = 2400
WINDOW_HEIGHT = 1400
PIXELS_PER_METRE = 5
FRAME_INTERVAL = 0.01

WALL_WIDTH = 175
GROUND_HEIGHT = 350
GROUND_Y = WINDOW_HEIGHT - GROUND_HEIGHT
VERTICAL_SHAFT_EDGE_COLOR = (50, 50, 50)
VERTICAL_SHAFT_MIDDLE_COLOR = (80, 80, 80)
GROUND_TOP_COLOR = (150, 100, 50)
GROUND_BOTTOM_COLOR = (100, 50, 0)

CANNON_BASE_LENGTH = 175
CANNON_BASE_HEIGHT = 64
CANNON_BASE_PIVOT_OFFSET_X = 131
CANNON_BASE_PIVOT_OFFSET_Y = 1
CANNON_BARREL_LENGTH = 189
CANNON_BARREL_DIAMETER = 31
CANNON_BARREL_PIVOT_OFFSET_X = 41
CANNON_BARREL_PIVOT_OFFSET_Y = 11
CANNON_BARREL_MUZZLE_OFFSET = 5
CANNON_WIDTH = CANNON_BASE_LENGTH + CANNON_BARREL_LENGTH - CANNON_BARREL_PIVOT_OFFSET_X

CANNONBALL_SCALE = 20
ARROW_LENGTH = 80
VELOCITY_ARROW_SCALE = 10
ACCELERATION_ARROW_SCALE = 10

FIRE_BUTTON_X = 15
CONTROLLING_FRAME_X = WALL_WIDTH + CANNON_WIDTH + 50
CONTROLLING_FRAME_Y = GROUND_Y

#Setting Window Sizes
SETTING_WINDOW_SIZES = {
    'Basic Parameters': (350, 250),
    'Visual Display': (300, 150),
    'Cannon Settings': (400, 350),
    'Cannonball Details': (500, 1000)
}

#Evironment Variables
MIN_GRAVITY = 0.5
MAX_GRAVITY = 500
MAX_SLIDER_GRAVITY = 50
DEFAULT_GRAVITY = 9.81

MAX_AIR_DENSITY = 100
MAX_SLIDER_AIR_DENSITY = 5
DEFAULT_AIR_DENSITY = 1.225

DEFAULT_DRAG_COEFFICIENT = 0.47

#Cannon Variables
MAX_CANNON_HEIGHT = 500
DEFAULT_CANNON_HEIGHT = 0

MIN_FIRING_ANGLE = 5
MAX_FIRING_ANGLE = 85
DEFAULT_FIRING_ANGLE = 45

MIN_INITIAL_VELOCITY = 10
MAX_INITIAL_VELOCITY = 1000
MAX_SLIDER_INITIAL_VELOCITY = 200
DEFAULT_CANNON_INITIAL_VELOCITY = 50

#Default Cannonball Variables
MIN_CANNONBALL_MASS = 50
MAX_CANNONBALL_MASS = 1000
MAX_SLIDER_CANNONBALL_MASS = 300
DEFAULT_CANNONBALL_MASS = 100

MIN_CANNONBALL_RADIUS = 0.1
MAX_CANNONBALL_RADIUS = 10
MAX_SLIDER_CANNONBALL_RADIUS = 4
DEFAULT_CANNONBALL_RADIUS = 1

MAX_TARGET_DISTANCE = 1500
MAX_TARGET_HEIGHT = 500
